import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '../components/Header'
import { Footer } from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
          <div className='mb-20'>
            <Header />
          </div>
          <div className='mb-18 mt-20'>
            {children}
          </div>
          <div className='fixed bottom-10 left-1/2 transform -translate-x-1/2'>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
